export const SUPPORTED_FORMATS = new Set(['js', 'ts', 'json'])

export const LANGUAGE_CODES = new Set([
  'sc',
  'tc',
  'en',
  'ja',
  'ko',
  'th',
  'id',
  'es',
  'fr',
  'de',
  'pt',
  'it',
  'ar',
  'tr',
  'ru',
  'vi',
])

export const HEADER_ALIASES = new Map(
  [
    ['key', 'key'],
    ['i18n key', 'key'],
    ['i18n_key', 'key'],
    ['english', 'en'],
    ['英文', 'en'],
    ['英语', 'en'],
    ['日本語', 'ja'],
    ['日语', 'ja'],
    ['日文', 'ja'],
    ['한국어', 'ko'],
    ['韩语', 'ko'],
    ['韓語', 'ko'],
    ['ไทย', 'th'],
    ['泰语', 'th'],
    ['泰文', 'th'],
    ['bahasa indonesia', 'id'],
    ['印尼语', 'id'],
    ['印尼文', 'id'],
    ['espanol', 'es'],
    ['español', 'es'],
    ['西班牙语', 'es'],
    ['西班牙文', 'es'],
    ['francais', 'fr'],
    ['français', 'fr'],
    ['法语', 'fr'],
    ['法文', 'fr'],
    ['deutsch', 'de'],
    ['德语', 'de'],
    ['德文', 'de'],
    ['português', 'pt'],
    ['portugues', 'pt'],
    ['葡萄牙语', 'pt'],
    ['葡萄牙文', 'pt'],
    ['italiano', 'it'],
    ['意大利语', 'it'],
    ['意大利文', 'it'],
    ['العربية', 'ar'],
    ['阿拉伯语', 'ar'],
    ['阿拉伯文', 'ar'],
    ['türkçe', 'tr'],
    ['turkce', 'tr'],
    ['土耳其语', 'tr'],
    ['土耳其文', 'tr'],
    ['русский', 'ru'],
    ['俄语', 'ru'],
    ['俄文', 'ru'],
    ['繁體中文', 'tc'],
    ['繁体中文', 'tc'],
    ['简体中文', 'sc'],
    ['簡體中文', 'sc'],
    ['越南语', 'vi'],
    ['越南文', 'vi'],
    ['tiếng việt', 'vi'],
  ].map(([header, code]) => [header.toLowerCase(), code]),
)
